name = "nostalgia-moderna"
main = "worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "."
binding = "ASSETS"

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "STATE"
id = "nostalgia"
